unitedstates/congress

requirements.txt
tasks/utils.py

[scrapelib](https://github.com/sunlightlabs/scrapelib) updated to `0.10`, and removed the `follow_robots` parameter and default behavior.
Unfortunately, removing the follow_robots keyword and *not* updating to `0.10` has the effect of enforcing robots.txt checking, which stops this project in its tracks (it depends on ignoring robots.txt).
So after merging, **anyone with this deployed needs to re-run `pip install -r requirements.txt`**.
I'll leave it to a project owner to merge.

update scrapelib to 0.10, remove follow_robots kwarg

---

tasks/bill_info.py

It would be nice to have the url from which the data is scraped.

Add source url in JSON data

---

requirements.txt

scrapelib 1.0 removes the deprecated urlopen method
this will prevent things from breaking until urlopen can be replaced

don't allow scrapelib 1.0 to be installed until urlopen calls are removed

---

.travis.yml

This issue suggests it's non-trivial for now:
https://github.com/travis-ci/travis-ci/issues/2312
But I have no idea why this only just started befalling us a few builds ago.

Fix Travis CI by dropping OS X builds

---

tasks/fdsys.py
tasks/utils.py

This is a follow-up of sorts from unitedstates/inspectors-general#149. `scrapelib.urlopen()` runs the entire response through `chardet`, which takes a long time on large binary files. This happens because `urlopen()` touches the `text` property defined by `requests`, which in turn runs `chardet` if the `encoding` property hasn't been set yet. Using `scrapelib.urlretrieve()` instead of `scrapelib.urlopen()` sidesteps the whole issue, see jamesturk/scrapelib#21.
In this PR, I replaced shelling out to `wget` with using `urlretrieve()`, which should be faster, since it runs in the same process. Moreover, `urlretreive()` raises exceptions on HTTP errors, which means the FDsys scraper can use the optimized path again, since that scraper depends on getting HTTP error codes back.

Use scrapelib.urlretrieve()

---

tasks/bills.py
tasks/fdsys.py

I ran into an issue where moving folders around in OS X was creating .DS_Store files, and when the system tried to parse those it died:
```
Traceback (most recent call last):
File "./import.py", line 72, in <module>
for id in to_fetch:
File "/Users/krues8dr/Sites/xcential.localhost/bill-importer/congress/tasks/bills.py", line 81, in get_bills_to_process
key = lambda x : int(x.replace(bill_type, ""))
File "/Users/krues8dr/Sites/xcential.localhost/bill-importer/congress/tasks/bills.py", line 81, in <lambda>
key = lambda x : int(x.replace(bill_type, ""))
ValueError: invalid literal for int() with base 10: '.DS_Store'
```
and
```
Traceback (most recent call last):
File "./import.py", line 72, in <module>
for id in to_fetch:
File "/Users/krues8dr/Sites/xcential.localhost/bill-importer/congress/ …
```

Handle .DS_Store files

---

tasks/fdsys.py
tasks/vote_info.py

First commit: #179 broke the fdsys scraper.
Second commit: Tweaking regexes in the vote category parser.

fix broken fdsys, vote category parsing regex tweaks

---

tasks/amendment_info.py
tasks/bill_info.py
tasks/utils.py

Our JSON and XML outputs for bills and amendments includes the THOMAS ids for sponsors and cosponsors. I think I kept it in the switch to the FDSys bulk data to remain as compatible as possible with earlier data files.
But..... Legislators are no longer getting THOMAS IDs. (Rep. Comer, who was recently sworn in, has cosponsored a bill, but has no THOMAS ID, and our scraper now fails on hconres17 because of it.) 
This:
* Removes all THOMAS IDs in output. We have bioguide ID fields in the same places.
* In the bill/amendment XML output, which I think I am the only consumer of, I replaced the thomas_id attribute with a bioguide_id attribute.
* There's some code changes in the GovTrack XML-specific code path (there's a `--govtrack` flag) that's just switching the THOMAS=>GovTrack ID …

drop THOMAS IDs from output, replace with bioguide in XML outputs

---

tasks/committee_meetings.py

`in` has been available since Python 2.2, 15 years ago.
Inspired by Lennart Regebro's PyCon 2017 presentation "Prehistoric Patterns in Python". Available at:
https://www.youtube.com/watch?v=V5-JH23Vk0I

Replace unnecessary calls to has_key

---

requirements.txt

Remove ipython from the requirements.txt file because:
1. IPython is not used anywhere in the repository
2. IPython 6+ is not compatible with Python 2.7
Issue: #224

Remove ipython from requirements.txt

---

README.md
scripts/bills.sh
scripts/statutes.sh
tasks/bills.py
tasks/fdsys.py
tasks/govinfo.py
tasks/utils.py

This is a work-in-progress to get feedback from anyone using the fdsys scraper. If I'm the only one using it, I'll just merge this once I have it working right in production on GovTrack.
GPO's Fdsys is being turned off at the end of the calendar year. GovInfo.gov, its replacement, is very similar but the sitemaps are organized a little differently and granules (which I used for getting Statutes at Large per-law PDFs) must be scraped diffrently.
Because the sitemap layout changed from being organized by year first and collection second to collection first and year second, I simplified the code a bit and as a result some output paths are different:
* The sitemap cache files have a totally new structure. Deleting the old files in cache/fdsys/sitemap is probably a good idea.
* "Granules" are …

switch fdsys scraper from fdsys to govinfo.gov

---

tasks/bill_info.py

Starting on Dec. 13 I started getting 689 bills (in the 116th Congress) with "committees" instead of "committee" in actions in the incoming GPO bulk data XML files. (Example: [HR 3](https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr3.xml)) It looks like currently 1,897 bills have this change. It appears that the data format change described at https://github.com/usgpo/bill-status/issues/147 was published early, and only in some bills.
Thankfully, our JSON data format for bills already held a list of committee codes, so no change to our data format was needed.
Once GPO has refreshed all of the bulk data files with the new <committees/> format, this code can be simplified to remove the `<committee>` case.
Fixes #245.

Incoming bill actions now have either <committee> or <committees> nodes

---

tasks/utils.py

I was getting this error when running the tool:
`[...]/unitedstates/congress/tasks/utils.py:33: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.`
This change specifies a loader so we don't get this deprecation message anymore. Seemed like `BaseLoader` was all we needed here. Some more info [here](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation#how-to-disable-the-warning).

Use yaml.BaseLoader when loading config

---

README.md

We already say to include `sudo` if necessary right before, so we don't need to include it in the shown command. Much better to err on the side of less permissions and let the user decide when/if it's appropriate to run `sudo` during installation of third party code.
Fixes #195.

Remove sudo from commands

---

requirements.txt
tasks/utils.py

This PR resolves #213 
I have made changes to how we use `scrapelib` based on the updated API of the 1.x versions.
The following [migration guide](https://scrapelib.readthedocs.io/en/latest/migration.html) was used as reference.

upddep scrapelib

---

.travis.yml
Dockerfile
README.md
contrib/beanstalkd.py
requirements.txt
tasks/bill_info.py
tasks/bills.py
tasks/committee_meetings.py
tasks/govinfo.py
tasks/statutes.py
tasks/upcoming_house_floor.py
tasks/utils.py
tasks/vote_info.py
tasks/votes.py
tasks/voteview.py
test/test_house_hearing.py

While it is possible to maintain backward compatibility with Python 2 and Python 3, it proved quite difficult for me to do, and ripping the bandaid off and converted to Python 3 seemed to be the better path.
This PR converts all python files to work with Python 3 as well as changing other metadata information to use Python 3.
Would love for people to test this branch out.

Convert congress codebase to Python 3

---

README.md

Some of the installation steps in the readme file were either outdated or do not work for current versions of Ubuntu. Namely, these two commands:
- ```mkvirtualenv congress```
- ```workon congress```

Updated documentation to include current installation steps

---

contrib/beanstalkd.py

New(ish) versions of PyYAML force you to be explicit about which Loader you wish to use (i.e. "the one that can execute code" or "the one that doesn't"). Since there's nothing special special about the `config.yml` here, we can use the boring one.
Failure to specify a loader will _raise an exception_ in current PyYAML.

Yaml safe-loader for Beanstalk contrib processing

---

congress/tasks/committee_meetings.py
congress/tasks/utils.py
congress/tasks/vote_info.py
congress/tasks/votes.py

This PR… 
- Upgrades the protocol of the URLs used to download from senate.gov and clerk.house.gov to use https. 
- Enables redirects on the request library (scraperlib)
[scraperlib's `allow_redirect` docs](https://jamesturk.github.io/scrapelib/reference/#scrapelib.Scraper.request)
Fixes: https://github.com/unitedstates/congress/issues/286

fix(votes, committee_meetings):  upgrade [senate.gov, clerk.house.gov] protocol to https

---

congress/tasks/amendment_info.py
congress/tasks/bills.py
congress/tasks/govinfo.py

I have a Python project wherein I import this package. The `from X import Y`[^1] buried in some of the data processing files requires `united-states-congress` to be the running project. Those imports crash the processing because Python tries to import them from *my* project instead.
Changing the `import`s to relative imports points Python to the right place. A possible alternative is fully-qualifying them.[^2]
[^1]: e.g. `from bills import output_for_bill`
[^2]: e.g. `from congress.tasks.bills import output_for_bill`

Fix relative imports

---

congress/tasks/amendment_info.py
congress/tasks/bills.py
congress/tasks/govinfo.py

The relative imports stop working when using usc-run bills from the main project. Changed to the fully qualified imports like suggested.  Not sure if there are any more imports elsewhere that should be updated to this style.

changed import to fully qualified imports

---

.gitattributes

When the package is zipped for distribution, the tests are redundant. There may be other unnecessary files, but the tests (plus fixtures) are 2/3 of the repository's footprint. Users don't need them in the package when they do something like this:
```sh
pip install https://github.com/unitedstates/congress/archive/main.zip
```
Is this silly, when you can easily download 500MB of data? Yes, it's a little silly.

Skip tarball archiving for /test/

---

Dockerfile

This PR fixes issues with the Dockerfile for building the United States Congress scraper Docker image. The changes include:
- Updating base image to debian:buster
- Using Python 3.7 (default in Debian Buster)
- Replacing pip with pip3
- Correcting Python path for congress.pth
- Creating necessary directories
Alternatively, the PYTHONPATH environment variable can be set instead of using congress.pth.
The modified Dockerfile has been tested locally and builds successfully. Please review and merge if everything looks good.
However, certain changes have been made in order to make it work - trying to get bills via the current setup of running things does not work. I've currently made it so you can just exec in and run the usc-run necessary, but other changes may be preferred.
Thanks!

Fixing Dockerfile - Debian Jessie no longer available

---

congress/tasks/govinfo.py

Sometimes I want to download bulk data just for certain types of bills (for example, just `h.r.` and `s.` bills). However, `usc-run govinfo --bulkdata=BILLSTATUS` fetches *all* bill types.
This PR adds a new argument to `usc-run govinfo` that allows you to select specific types of bills to download.
```shell
usc-run govinfo --bulkdata=BILLSTATUS  --type=hres # Only fetch House Resolutions
```
Will only fetch H.R.'s for the 118th Congress:
```shell
usc-run govinfo --bulkdata=BILLSTATUS --congress=118 --type=hr
```
Will only fetch Joint Resolutions:
```shell
usc-run govinfo --bulkdata=BILLSTATUS --congress=118 --type=hjres,sjres
```

Bill `--type` filter when downloading with `usc-run govinfo`.

---

congress/tasks/bill_info.py

Reference bill: `s4085-118`
Several bills in session 118 are failing to download because the `sponsor_for` logic is failing to parse the sponsor fullName.
In particular, bills sponsored by `Rescom. González-Colón, Jenniffer [R-PR-At Large]` are failing because the regex doesn't account for `Rescom.`
Reference bills: `['s4085-118', 's1805-118', 's1331-118']`
Fixes a `KeyError` issue with accessing missing properties for the bills above.

Add Rescom. in sponsor_for in bill_info
